// GENERATED by compiler/figma/normalize.mjs from Figma vector export (node 12246:5764 / icon instance).
// FIXTURE: this is the Figma placeholder icon used to demonstrate the leadingIcon/trailingIcon slot.
// It is rendered by the visual harness to reproduce the specimen and is NOT part of the public Button API
// (see .design-compiler/ir/button.semantics.json -> fixtureIr). Do not import it from product code.
import type { SVGProps } from "react";
export function PlaceholderCircleIcon({ title, ...props }: SVGProps<SVGSVGElement> & { title?: string }) {
  return (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" focusable="false" aria-hidden={title ? undefined : true} role={title ? "img" : undefined} {...props}>
      {title ? <title>{title}</title> : null}
      <g transform="translate(-12 -9)">
        <path stroke="currentColor" d="M20 23.6666C23.6819 23.6666 26.6667 20.6819 26.6667 17C26.6667 13.3181 23.6819 10.3333 20 10.3333C16.3181 10.3333 13.3333 13.3181 13.3333 17C13.3333 20.6819 16.3181 23.6666 20 23.6666Z" strokeWidth={1.5} strokeLinecap="round" strokeLinejoin="round" />
      </g>
    </svg>
  );
}