/**
 * Rule → artifact emission (FIGMA_SLICING.md §8, §12).
 *
 * Takes the mined rule table and emits:
 *   - token list (CSS custom properties + figma evidence)
 *   - button.theme.css : the paint/structure matrix as selector -> variables, plus the base rules
 *   - the set of unsupported combinations (axes that Figma does not define)
 *
 * No model call. Every emitted value is an observed Figma value.
 */

import { existsSync, readFileSync } from "node:fs";

/** Measured renderer offsets (see .design-compiler/ir/renderer-calibration.json) — not Figma properties. */
const calibration = (() => {
  const path = ".design-compiler/ir/renderer-calibration.json";
  if (!existsSync(path)) return null;
  try {
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    return null;
  }
})();

const px = (v) => (typeof v === "number" ? `${+v.toFixed(3)}px` : v);
/** Rule values arrive as scalars or JSON-encoded arrays (the signature flattener stringifies arrays). */
const asArray = (v) => {
  if (Array.isArray(v)) return v;
  if (typeof v === "string" && v.startsWith("[")) {
    try {
      const parsed = JSON.parse(v);
      return Array.isArray(parsed) ? parsed : null;
    } catch {
      return null;
    }
  }
  return null;
};
const tuple = (v) => {
  const arr = asArray(v);
  return arr ? arr.map(px).join(" ") : v;
};

/** property path (as mined) -> { varName, transform, scope } */
const VAR_MAP = {
  "box.h": { name: "height", scope: "size", fn: px },
  padding: { name: "padding", scope: "size", skip: true },
  gap: { name: "gap", scope: "size", fn: px },
  radius: { name: "radius", scope: "hierarchy", fn: px },
  fill: { name: "fill", scope: "hierarchy", fn: (v) => v ?? "transparent" },
  shadow: { name: "shadow", scope: "hierarchy", fn: (v) => (v ? v.split(/,(?![^(]*\))/).map((l) => l.trim()).reverse().join(", ") : "none") },
  nodeOpacity: { name: "opacity", scope: "hierarchy", fn: String },
  "label.color": { name: "fg", scope: "hierarchy", fn: (v) => v ?? "currentColor" },
  "label.box.h": { name: "label-height", scope: "size", fn: px },
  labelOverrides: { name: "label-decoration", scope: "hierarchy", fn: (v) => (String(v).includes("UNDERLINE") ? "underline" : "none") },
  labelWrapperPadding: { name: "label-padding", scope: "hierarchy", fn: (v) => (asArray(v) ? `${px(asArray(v)[0] ?? 0)} ${px(asArray(v)[1] ?? 0)}` : "0px 0px") },
  "label.fontFamily": { name: "font-family", scope: "size", fn: (v) => `'${v}', sans-serif` },
  "label.fontWeight": { name: "font-weight", scope: "size", fn: String },
  "label.fontSize": { name: "font-size", scope: "size", fn: px },
  "label.lineHeight": { name: "line-height", scope: "size", fn: px },
  "label.letterSpacing": { name: "letter-spacing", scope: "size", fn: (v) => `${v}px` },
  "icons[0].box.w": { name: "icon", scope: "size", fn: px },
  "icons[0].opacity": { name: "icon-opacity", scope: "hierarchy", fn: String },
  "icons[0].color": { name: "icon-color", scope: "hierarchy", fn: (v) => v ?? "currentColor" },
};

/** Ring: Figma stroke -> inset ring (solid border or gradient highlight), width preserved. */
function ringCss(stroke, iconStrokeUnits) {
  if (!stroke || stroke.type == null) return { width: "0px", image: "none" };
  const width = px(stroke.weight);
  if (stroke.type === "GRADIENT_LINEAR") {
    const stops = stroke.stops.filter((s) => s.color != null);
    return { width, image: `linear-gradient(180deg, ${stops.map((s) => `${s.color} ${s.at * 100}%`).join(", ")})` };
  }
  return { width, image: stroke.color ?? "none" };
}

/** Public styling contract: DOM attribute + the value the consumer writes, never Figma's raw axis value. */
export const DOM_CONTRACT = {
  Hierarchy: { attr: "data-variant", value: (v) => v.toLowerCase().replace(/ /g, "-") },
  Size: { attr: "data-size", value: (v) => v },
  State: { attr: "data-state", value: (v) => v.toLowerCase() },
  "Icon only": { attr: "data-icon-only", value: (v) => v.toLowerCase() },
};
const sel = (axis, value) => `[${DOM_CONTRACT[axis].attr}="${DOM_CONTRACT[axis].value(value)}"]`;

export function emitThemeCss({ rules, variants }) {
  const axisValues = (axis) => [...new Set(variants.map((v) => v.axes[axis]))];
  const blocks = [];
  const used = {};
  const header = [
    "/* GENERATED by compiler/figma/emit.mjs from .design-compiler/ir/button.rules.json — do not edit.",
    "   Every declaration is an observed Figma value or a deterministic derivation of one.",
    "   Emitted inside @layer components so consumer utilities (Tailwind) override it: <Button className=\"rounded-full\" />. */",
    "@layer components {",
  ];
  const body = [];

  // ---- resolve each mined property into (selector-scope, var, value)
  for (const [property, rule] of Object.entries(rules)) {
    const map = VAR_MAP[property];
    if (!map || map.skip || !rule.determinant || typeof map.fn !== "function") continue;
    used[property] = map;
    for (const [key, value] of Object.entries(rule.values)) {
      const names = rule.determinant;
      const parts = key.split("|");
      const selector = names.map((n, i) => sel(n, parts[i])).join("");
      const varName = `--dsb-${map.scope}-${map.name}`;
      const value$ = map.fn(value);
      if (value$ === null || value$ === undefined || String(value$).includes("undefined")) continue;
      blocks.push({ selector, varName, value: String(value$) });
    }
  }

  // ---- ring (stroke) is matrix-valued in Figma: primary uses a gradient, secondary a solid border
  const strokeRule = rules["stroke"];
  for (const variant of variants) {
    const key = strokeRule.determinant.map((n) => variant.axes[n]).join("|");
    const stroke = variant.sig.stroke;
    if (!stroke) continue;
    const { width, image } = ringCss(stroke, variant.sig.icons[0]?.strokeWeight);
    const selector = strokeRule.determinant.map((n, i) => sel(n, key.split("|")[i])).join("");
    blocks.push({ selector, varName: "--dsb-ring-width", value: width, dedupe: true });
    blocks.push({ selector, varName: "--dsb-ring-image", value: image, dedupe: true });
  }
  // ---- icon stroke width is authored in SVG user units (viewBox stays 16x16 for every size)
  for (const variant of variants) {
    const iconBox = variant.sig.icons[0]?.box?.w;
    const vectorBox = variant.sig.icons[0]?.parts?.[0]?.box?.w;
    const weight = variant.sig.icons[0]?.parts?.[0]?.strokeWeight ?? variant.sig.icons[0]?.strokeWeight;
    if (!iconBox || !vectorBox || weight == null) continue;
    const units = +(weight / (iconBox / 16)).toFixed(4);
    blocks.push({
      selector: sel("Size", variant.axes.Size),
      varName: "--dsb-icon-stroke",
      value: String(units),
      dedupe: true,
    });
  }

  for (const variant of variants) {
    const slotW = variant.sig.spinner?.box?.w ?? variant.sig.icons[0]?.box?.w;
    const weight = variant.sig.spinner?.track?.strokeWeight;
    if (!slotW || weight == null) continue;
    blocks.push({ selector: `[data-size="${variant.axes.Size}"]`, varName: "--dsb-spinner-stroke", value: String(+(weight * (16 / slotW)).toFixed(3)), dedupe: true });
  }

  // ---- spinner colours (geometry is size-independent once normalised into the 16-unit slot)
  for (const [property, varName] of [
    ["spinner.track.color", "--dsb-spinner-track-color"],
    ["spinner.arc.color", "--dsb-spinner-arc-color"],
    ["spinner.track.opacity", "--dsb-spinner-track-opacity"],
  ]) {
    const rule = rules[property];
    if (!rule?.determinant) continue;
    for (const [key, value] of Object.entries(rule.values)) {
      if (value === null || value === undefined) continue;
      const parts = key.split("|");
      const selector = rule.determinant.map((n, i) => sel(n, parts[i])).join("");
      blocks.push({ selector, varName, value: String(value), dedupe: true });
    }
  }

  // ---- padding: symmetric in the source, emitted as logical pairs so `dir=rtl` and utilities both work
  const paddingRule = rules.padding;
  if (paddingRule?.determinant) {
    for (const [key, value] of Object.entries(paddingRule.values)) {
      const arr = asArray(value);
      if (!arr) continue;
      const parts = key.split("|");
      const selector = paddingRule.determinant.map((n, i) => sel(n, parts[i])).join("");
      blocks.push({ selector, varName: "--dsb-size-padding-block", value: `${px(arr[0])} ${px(arr[2])}`, dedupe: true });
      blocks.push({ selector, varName: "--dsb-size-padding-inline", value: `${px(arr[1])} ${px(arr[3])}`, dedupe: true });
    }
  }

  // ---- state selectors: every forced `[data-state=…]` block also gets its natural CSS selector, so the
  //      component reacts to real interaction while visual tests can force a state (§8: Figma state -> CSS state).
  // keyed by the public (lowercase) state value, since selectors carry the public contract
  const STATE_ALIAS = {
    default: (s) => s.replace(/\[data-state="default"\]/, ""),
    hover: (s) => s.replace(/\[data-state="hover"\]/, ":hover:not([data-state])"),
    focused: (s) => s.replace(/\[data-state="focused"\]/, ":focus-visible:not([data-state])"),
    disabled: (s) => s.replace(/\[data-state="disabled"\]/, ":disabled"),
    loading: (s) => s.replace(/\[data-state="loading"\]/, "[aria-busy=\"true\"]"),
  };
  const expand = (selector) => {
    const state = /\[data-state="([^"]+)"\]/.exec(selector)?.[1];
    if (!state) return [selector];
    const natural = STATE_ALIAS[state.toLowerCase()]?.(selector) ?? selector;
    return natural === selector ? [selector] : [natural, selector];
  };

  // ---- calibrated renderer offsets (measured, recorded, never guessed)
  const underline = calibration?.["link-underline-offset"]?.sizes;
  if (underline) {
    for (const [size, offset] of Object.entries(underline)) {
      blocks.push({ selector: `[data-size="${size}"]`, varName: "--dsb-label-underline-offset", value: `${offset}px`, dedupe: true });
    }
  }

  const bySelector = new Map();
  for (const { selector, varName, value } of blocks) {
    for (const sel of expand(selector)) {
      if (!bySelector.has(sel)) bySelector.set(sel, new Map());
      bySelector.get(sel).set(varName, value);
    }
  }

  body.push("[data-ds-button] {");
  body.push("  box-sizing: border-box;");
  body.push("  position: relative;");
  body.push("  display: inline-flex;");
  body.push("  flex: none;");
  body.push("  align-items: center;");
  body.push("  justify-content: center;");
  body.push("  overflow: clip;");
  body.push("  white-space: nowrap;");
  body.push("  user-select: none;");
  body.push("  margin: 0;");
  body.push("  border: 0;");
  body.push("  appearance: none;");
  body.push("  cursor: pointer;");
  body.push("  height: var(--dsb-size-height);");
  // logical properties: identical values, but correct under dir=rtl, and overridable by utilities
  body.push("  padding-block: var(--dsb-size-padding-block);");
  body.push("  padding-inline: var(--dsb-size-padding-inline);");
  body.push("  gap: var(--dsb-size-gap);");
  body.push("  border-radius: var(--dsb-hierarchy-radius, 0);");
  body.push("  background: var(--dsb-hierarchy-fill, transparent);");
  body.push("  color: var(--dsb-hierarchy-fg, currentColor);");
  body.push("  box-shadow: var(--dsb-hierarchy-shadow, none);");
  body.push("  opacity: var(--dsb-hierarchy-opacity, 1);");
  body.push("  font-family: var(--dsb-size-font-family);");
  body.push("  font-weight: var(--dsb-size-font-weight);");
  body.push("  font-size: var(--dsb-size-font-size);");
  body.push("  line-height: var(--dsb-size-line-height);");
  body.push("  letter-spacing: var(--dsb-size-letter-spacing);");
  body.push("  transition: background-color var(--ds-motion-duration-fast) var(--ds-motion-ease-standard);");
  body.push("}");
  body.push("");
  body.push("/* Figma stroke: inset ring that does not affect the box model (a real border would widen the hug box). */");
  body.push("[data-ds-button]::after {");
  body.push("  content: \"\";");
  body.push("  position: absolute;");
  body.push("  inset: 0;");
  body.push("  border-radius: inherit;");
  body.push("  padding: var(--dsb-ring-width, 0px);");
  body.push("  background: var(--dsb-ring-image, none);");
  body.push("  pointer-events: none;");
  body.push("  mask-image: linear-gradient(#000 0 0), linear-gradient(#000 0 0);");
  body.push("  mask-clip: content-box, border-box;");
  body.push("  mask-composite: exclude;");
  body.push("}");
  body.push("");
  body.push("[data-ds-button] [data-slot=\"icon\"],");
  body.push("[data-ds-button] [data-slot=\"spinner\"] {");
  body.push("  display: inline-flex;");
  body.push("  flex: none;");
  body.push("  align-items: center;");
  body.push("  justify-content: center;");
  body.push("  width: var(--dsb-size-icon);");
  body.push("  height: var(--dsb-size-icon);");
  // Figma expresses the dimmed icon/spinner as instance opacity, so both slots share it.
  body.push("  opacity: var(--dsb-hierarchy-icon-opacity, 1);");
  body.push("}");
  body.push("[data-ds-button] [data-slot=\"icon\"] {");
  body.push("  color: var(--dsb-hierarchy-icon-color, currentColor);");
  body.push("}");
  body.push("[data-ds-button] [data-slot=\"icon\"] svg,");
  body.push("[data-ds-button] [data-slot=\"spinner\"] svg { width: 100%; height: 100%; }");
  body.push("[data-ds-button] [data-slot=\"icon\"] path { stroke-width: var(--dsb-icon-stroke); }");
  body.push("[data-ds-button] [data-slot=\"spinner\"] path {");
  body.push("  fill: none;");
  body.push("  stroke-width: var(--dsb-spinner-stroke, 2);");
  body.push("  stroke-linecap: round;");
  body.push("  stroke-linejoin: round;");
  body.push("}");
  body.push("[data-ds-button] [data-slot=\"spinner\"] .track { stroke: var(--dsb-spinner-track-color); opacity: var(--dsb-spinner-track-opacity, 0.3); }");
  body.push("[data-ds-button] [data-slot=\"spinner\"] .arc { stroke: var(--dsb-spinner-arc-color); }");
  body.push("");
  body.push("[data-ds-button] [data-slot=\"label\"] {");
  body.push("  display: inline-flex;");
  body.push("  flex: none;");
  // `--dsb-label-width` is the Figma text-node width, so the box must be content-box: the inline padding
  // (Figma's "Text padding" frame) sits outside it. Global border-box would silently drop 2px per side.
  body.push("  box-sizing: content-box;");
  body.push("  height: var(--dsb-size-label-height);");
  body.push("  inline-size: var(--dsb-label-width, auto);");
  body.push("  text-decoration: var(--dsb-hierarchy-label-decoration, none);");
  body.push("  text-underline-offset: var(--dsb-label-underline-offset, auto);");
  body.push("  padding-inline: var(--dsb-hierarchy-label-padding, 0px);");
  body.push("}");
  body.push("");
  // Emission order matters: the natural state selectors (:hover, :focus-visible, [aria-busy], :disabled)
  // have equal specificity, so a later rule wins. Priority must be Default < Hover < Focused < Loading <
  // Disabled — otherwise hovering while keyboard-focused silently removes the focus ring.
  const stateRank = (selector) => {
    if (/\[data-state=/.test(selector)) return 5; // forced states: highest specificity, keep last
    if (/:hover/.test(selector)) return 1;
    if (/:focus-visible/.test(selector)) return 2;
    if (/aria-busy/.test(selector)) return 3;
    if (/:disabled/.test(selector)) return 4;
    return 0;
  };
  const specificityish = (selector) => (selector.match(/\[/g) ?? []).length + (selector.match(/:(?!:)/g) ?? []).length;
  const ordered = [...bySelector.entries()].sort(
    (a, b) => stateRank(a[0]) - stateRank(b[0]) || specificityish(a[0]) - specificityish(b[0]) || a[0].localeCompare(b[0]),
  );
  for (const [selector, vars] of ordered) {
    body.push(`${selector} {`);
    for (const [k, v] of [...vars.entries()].sort()) body.push(`  ${k}: ${v};`);
    body.push("}");
  }
  body.push("");
  body.push("/* production hardening: honour user motion and forced-colour preferences */");
  body.push("@media (prefers-reduced-motion: reduce) {");
  body.push("  [data-ds-button] { transition: none; }");
  body.push("}");
  body.push("@media (forced-colors: active) {");
  body.push("  [data-ds-button] { border: 1px solid ButtonBorder; }");
  body.push("  [data-ds-button]:disabled { color: GrayText; border-color: GrayText; }");
  body.push("}");
  body.push("");
  return [...header, ...body, "}"].join("\n");
}

/** Combinations the Figma set does not define (§12) — emitted, never invented. */
export function unsupportedCombos(variants, axesValues) {
  const present = new Set(variants.map((v) => [v.axes.Size, v.axes.Hierarchy, v.axes.State, v.axes["Icon only"]].join("|")));
  const missing = [];
  for (const size of axesValues.Size)
    for (const hierarchy of axesValues.Hierarchy)
      for (const state of axesValues.State)
        for (const iconOnly of axesValues["Icon only"])
          if (!present.has([size, hierarchy, state, iconOnly].join("|"))) missing.push({ size, hierarchy, state, iconOnly });
  return missing;
}
