// GENERATED by compiler/figma/compile.mjs from the Figma loading variants' ellipse geometry.
// Figma keeps the spinner stroke an absolute width, so the centreline radius differs per size; each size
// carries its own normalised arc (16-unit slot). Colour and stroke width come from button.theme.css.
// Do not edit by hand.
import type { SVGProps } from "react";

type SpinnerSize = "xs" | "sm" | "md" | "lg" | "xl";

const PATHS: Record<SpinnerSize, { track: string; arc: string }> = {
  lg: { track: "M14.4 8A6.4 6.4 0 1 1 1.6 8A6.4 6.4 0 1 1 14.4 8", arc: "M8 1.6A6.4 6.4 0 0 1 14.4 8" },
  md: { track: "M14.4 8A6.4 6.4 0 1 1 1.6 8A6.4 6.4 0 1 1 14.4 8", arc: "M8 1.6A6.4 6.4 0 0 1 14.4 8" },
  sm: { track: "M14.4 8A6.4 6.4 0 1 1 1.6 8A6.4 6.4 0 1 1 14.4 8", arc: "M8 1.6A6.4 6.4 0 0 1 14.4 8" },
  xl: { track: "M14.4 8A6.4 6.4 0 1 1 1.6 8A6.4 6.4 0 1 1 14.4 8", arc: "M8 1.6A6.4 6.4 0 0 1 14.4 8" },
  xs: { track: "M14.2 8A6.2 6.2 0 1 1 1.8 8A6.2 6.2 0 1 1 14.2 8", arc: "M8 1.8A6.2 6.2 0 0 1 14.2 8" },
};

export function ButtonSpinnerIcon({ size = "xs", ...props }: SVGProps<SVGSVGElement> & { size?: SpinnerSize }) {
  const path = PATHS[size] ?? PATHS.xs;
  return (
    <svg viewBox="0 0 16 16" fill="none" aria-hidden="true" focusable="false" {...props}>
      <path className="track" d={path.track} />
      <path className="arc" d={path.arc} />
    </svg>
  );
}
