import { Component, type ReactNode, useEffect, useMemo, useRef, useState } from "react";
import { createRoot, type Root } from "react-dom/client";
import catalog from "../.design-compiler/catalog.json";
import "../registry/untitledui/styles/globals.css";
import "./styles/fonts.css";

/**
 * The component catalog: every registry item, with a live preview where the payload exposes a component.
 *
 * The index is `.design-compiler/catalog.json`, generated by `node compiler/catalog/build.mjs` from the
 * registry index — this page never hard-codes membership. Previews are lazy module imports, so only the
 * components on screen are loaded; components that need props report that instead of rendering blank.
 */
const MODULES = import.meta.glob("/registry/untitledui/**/*.tsx") as Record<string, () => Promise<Record<string, unknown>>>;
const loadModule = (path: string | null) => (path ? MODULES[`/${path}`] ?? MODULES[path] : undefined);

type Item = (typeof catalog.items)[number];

/** `null` in the catalog's preview props means "a text-like prop the source declares without a default". */
const previewPropsFor = (item: Item) => {
  const preset: Record<string, unknown> = {};
  const humanized = item.id.replace(/-/g, " ").replace(/^./, (c) => c.toUpperCase());
  for (const [prop, value] of Object.entries(item.previewProps ?? {})) preset[prop] = value === null ? humanized : value;
  return preset;
};

/** A component that renders nothing without props still renders *something*; this decides which is which. */
const rendersSomething = (node: HTMLElement | null) => Boolean(node && (node.querySelector("*") || node.textContent?.trim()));

class PreviewErrorBoundary extends Component<{ children: ReactNode; onError: (message: string) => void }, { failed: boolean }> {
  state = { failed: false };
  static getDerivedStateFromError() {
    return { failed: true };
  }
  componentDidCatch(error: Error) {
    // never update the parent during the commit that just failed
    queueMicrotask(() => this.props.onError(error.message));
  }
  render() {
    return this.state.failed ? null : this.props.children;
  }
}

/**
 * One render attempt. Untitled UI components take props, so a bare render may produce nothing: after a
 * short settle the attempt retries once passing the item name as children, then reports instead of looping.
 */
function Attempt({ Component, props, label, onFail }: { Component: (props: Record<string, unknown>) => ReactNode; props: Record<string, unknown>; label: string; onFail: (message: string) => void }) {
  const [attempt, setAttempt] = useState<0 | 1>(0);
  const host = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (attempt !== 0) return;
    const id = window.setTimeout(() => {
      if (!rendersSomething(host.current)) setAttempt(1);
    }, 150);
    return () => window.clearTimeout(id);
  }, [attempt]);

  // attempt 1 only adds children — never a prop the component does not declare
  const applied = attempt === 0 || "children" in props ? props : { ...props, children: label };
  return (
    <div ref={host} className="contents">
      <PreviewErrorBoundary key={attempt} onError={(message) => (attempt === 0 ? setAttempt(1) : onFail(`needs props — ${message}`))}>
        <Component {...applied} />
      </PreviewErrorBoundary>
    </div>
  );
}

/**
 * Renders the item in its own React root. A component that throws while mounting (or that needs a provider)
 * can then only tear down its own preview — the catalog itself stays mounted, which a shared tree could not
 * guarantee.
 */
function Preview({ item }: { item: Item }) {
  const host = useRef<HTMLDivElement>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [inView, setInView] = useState(false);

  // A catalog of hundreds of items must not hold hundreds of mounted roots: previews mount near the
  // viewport and release when scrolled away, so the page cost tracks what the reader can actually see.
  useEffect(() => {
    const element = host.current;
    if (!element) return;
    const observer = new IntersectionObserver((entries) => setInView(entries.some((e) => e.isIntersecting)), { rootMargin: "240px" });
    observer.observe(element);
    return () => observer.disconnect();
  }, []);

  useEffect(() => {
    const element = host.current;
    const loader = loadModule(item.module);
    const exportName = item.exportName;
    if (!element || !inView) return;
    if (!loader || !exportName) {
      setMessage("no component export to preview");
      return;
    }
    let cancelled = false;
    let root: Root | null = null;
    loader()
      .then((mod) => {
        if (cancelled) return;
        const candidate = typeof mod[exportName] === "function" ? mod[exportName] : "default" in mod ? mod.default : undefined;
        if (typeof candidate !== "function") {
          setMessage("no component export to preview");
          return;
        }
        root = createRoot(element, { onCaughtError: () => {}, onUncaughtError: () => {} });
        root.render(
          <Attempt
            Component={candidate as (props: Record<string, unknown>) => ReactNode}
            props={previewPropsFor(item)}
            label={item.id.replace(/-/g, " ").replace(/^./, (c) => c.toUpperCase())}
            onFail={setMessage}
          />,
        );
      })
      .catch((error: unknown) => {
        if (!cancelled) setMessage(error instanceof Error ? error.message : String(error));
      });
    return () => {
      cancelled = true;
      // unmount after React finishes the commit that may be in flight
      queueMicrotask(() => root?.unmount());
    };
  }, [inView, item.exportName, item.id, item.module]);

  return (
    <div className="flex min-h-[7rem] flex-col">
      <div ref={host} className="flex flex-1 items-center justify-center gap-3 p-4">
        {!inView ? <span className="text-[11px] text-utility-gray-400">…</span> : null}
      </div>
      {message ? <p className="px-3 pb-2 text-[11px] leading-4 text-utility-gray-500">{message}</p> : null}
    </div>
  );
}

const Chip = ({ active, children, onClick, title }: { active?: boolean; children: ReactNode; onClick: () => void; title?: string }) => (
  <button
    type="button"
    title={title}
    onClick={onClick}
    className={`rounded-full border px-2.5 py-1 text-xs transition ${
      active ? "border-utility-brand-600 bg-utility-brand-50 text-utility-brand-700" : "border-utility-gray-200 bg-white text-utility-gray-700 hover:bg-utility-gray-50"
    }`}
  >
    {children}
  </button>
);

function Card({ item }: { item: Item }) {
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(false);
  return (
    <div className="flex flex-col overflow-hidden rounded-xl border border-utility-gray-200 bg-white">
      {open ? (
        <Preview item={item} />
      ) : (
        <div className="flex min-h-[7rem] items-center justify-center p-4">
          <button type="button" onClick={() => setOpen(true)} className="rounded-lg border border-utility-gray-300 px-3 py-1.5 text-xs font-medium text-utility-gray-700 hover:bg-utility-gray-50">
            Show preview
          </button>
        </div>
      )}
      <div className="border-t border-utility-gray-100 p-3">
        <div className="flex items-start justify-between gap-2">
          <p className="truncate text-sm font-semibold text-utility-gray-900">{item.id}</p>
          <span className="shrink-0 rounded bg-utility-gray-100 px-1.5 py-0.5 text-[11px] text-utility-gray-600">{item.tier}</span>
        </div>
        <p className="mt-0.5 truncate text-[11px] text-utility-gray-500">{item.upstream ?? item.module ?? "—"}</p>
        <div className="mt-2 flex flex-wrap items-center gap-1 text-[11px]">
          <span className={`rounded px-1.5 py-0.5 ${item.status === "VERIFIED" ? "bg-utility-green-50 text-utility-green-700" : "bg-utility-gray-100 text-utility-gray-600"}`}>{item.status}</span>
          {item.figmaPresence ? <span className="rounded bg-utility-gray-100 px-1.5 py-0.5 text-utility-gray-600">{item.figmaPresence}</span> : null}
          {item.engine ? <span className="rounded bg-utility-gray-100 px-1.5 py-0.5 text-utility-gray-600">{item.engine}</span> : null}
          <span className="rounded bg-utility-gray-100 px-1.5 py-0.5 text-utility-gray-600">{item.layer}</span>
        </div>
        {item.install ? (
          <button
            type="button"
            onClick={() => {
              navigator.clipboard?.writeText(item.install as string);
              setCopied(true);
              window.setTimeout(() => setCopied(false), 1200);
            }}
            className="mt-2 w-full truncate rounded-md bg-utility-gray-900 px-2 py-1.5 text-left font-mono text-[11px] text-white hover:bg-utility-gray-800"
            title="Copy install command"
          >
            {copied ? "copied" : item.install}
          </button>
        ) : null}
      </div>
    </div>
  );
}

function Section({ title, subtitle, children }: { title: string; subtitle: string; children: ReactNode }) {
  return (
    <section className="mt-10">
      <h2 className="text-lg font-semibold text-utility-gray-900">{title}</h2>
      <p className="mt-0.5 text-sm text-utility-gray-600">{subtitle}</p>
      <div className="mt-4">{children}</div>
    </section>
  );
}

function Catalog() {
  const [query, setQuery] = useState("");
  const [group, setGroup] = useState<string | null>(null);
  const [layer, setLayer] = useState<string | null>(null);
  const [tier, setTier] = useState<string | null>(null);
  const [onlyInstallable, setOnlyInstallable] = useState(true);

  const layers = useMemo(() => Object.keys(catalog.totals.byLayer).sort(), []);
  const tiers = useMemo(() => Object.keys(catalog.totals.byTier).sort(), []);
  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    return (catalog.items as Item[]).filter(
      (i) =>
        (!onlyInstallable || i.installable) &&
        (!group || i.group === group) &&
        (!layer || i.layer === layer) &&
        (!tier || i.tier === tier) &&
        (!q || [i.id, i.upstream, i.exportName, i.figma, i.group].some((v) => typeof v === "string" && v.toLowerCase().includes(q))),
    );
  }, [query, group, layer, tier, onlyInstallable]);

  const groupCounts = useMemo(
    () =>
      (catalog.items as Item[]).reduce<Record<string, number>>((m, i) => ((m[i.group] = (m[i.group] ?? 0) + 1), m), {}),
    [],
  );

  return (
    <div className="min-h-screen bg-utility-gray-50">
      <header className="border-b border-utility-gray-200 bg-white">
        <div className="mx-auto max-w-[110rem] px-6 py-5">
          <h1 className="text-xl font-semibold text-utility-gray-900">Component catalog</h1>
          <p className="mt-1 text-sm text-utility-gray-600">
            {catalog.totals.items} registry items · {catalog.totals.installable} installable · {catalog.totals.byLayer.component ?? 0} components ·{" "}
            {catalog.groups.length} groups · {catalog.totals.previewable} previewable · source: <code className="font-mono text-xs">{catalog.source}</code>
          </p>
          <div className="mt-4 flex flex-wrap items-center gap-2">
            <input
              value={query}
              onChange={(event) => setQuery(event.target.value)}
              placeholder="Search by name, path, export or Figma set…"
              className="w-80 rounded-lg border border-utility-gray-300 px-3 py-2 text-sm outline-none focus:border-utility-brand-500"
            />
            <Chip active={onlyInstallable} onClick={() => setOnlyInstallable(!onlyInstallable)} title="Items installable through the CLI">
              installable only
            </Chip>
            {layers.map((l) => (
              <Chip key={l} active={layer === l} onClick={() => setLayer(layer === l ? null : l)}>
                {l} {catalog.totals.byLayer[l as keyof typeof catalog.totals.byLayer]}
              </Chip>
            ))}
            {tiers.map((t) => (
              <Chip key={t} active={tier === t} onClick={() => setTier(tier === t ? null : t)}>
                {t}
              </Chip>
            ))}
            {group ? (
              <Chip active onClick={() => setGroup(null)}>
                group: {group} ✕
              </Chip>
            ) : null}
          </div>
          <p className="mt-3 flex flex-wrap gap-1.5 text-[11px]">
            {catalog.groups.map((g) => (
              <button
                key={g}
                type="button"
                onClick={() => setGroup(group === g ? null : g)}
                className={`rounded px-1.5 py-0.5 ${group === g ? "bg-utility-brand-600 text-white" : "bg-utility-gray-100 text-utility-gray-600 hover:bg-utility-gray-200"}`}
              >
                {g} {groupCounts[g]}
              </button>
            ))}
          </p>
          <p className="mt-3 text-xs text-utility-gray-500">
            Other views:{" "}
            <a className="underline" href="/adopted.html">
              adopted specimen
            </a>{" "}
            ·{" "}
            <a className="underline" href="/parity.html">
              Figma parity
            </a>{" "}
            ·{" "}
            <a className="underline" href="/pro.html">
              PRO compositions
            </a>{" "}
            ·{" "}
            <a className="underline" href="/behavior.html">
              behaviour states
            </a>{" "}
            ·{" "}
            <a className="underline" href="/specimen.html">
              geometry
            </a>{" "}
            ·{" "}
            <a className="underline" href="/grid.html">
              compiler matrix
            </a>
          </p>
        </div>
      </header>

      <main className="mx-auto max-w-[110rem] px-6 pb-16">
        <Section title="Registry items" subtitle={`${filtered.length} shown${group ? ` in ${group}` : ""}${layer ? ` · ${layer}` : ""}${tier ? ` · tier ${tier}` : ""} — previews load on demand.`}>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-5">
            {filtered.map((item) => (
              <Card key={item.id} item={item} />
            ))}
          </div>
          {filtered.length === 0 ? <p className="text-sm text-utility-gray-500">Nothing matches those filters.</p> : null}
        </Section>

        <Section title="PRO compositions" subtitle="Licensed PRO families resolved outside the OSS payload; artifacts stay private.">
          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {catalog.proFamilies.map((f) => (
              <div key={f.name} className="rounded-xl border border-utility-gray-200 bg-white p-4">
                <p className="text-sm font-semibold text-utility-gray-900">{f.name}</p>
                <p className="mt-1 text-[11px] text-utility-gray-500">
                  {f.status} · {f.classification}
                  {f.artifact ? ` · ${f.artifact}` : ""}
                </p>
              </div>
            ))}
          </div>
        </Section>

        <Section title="Figma-verified canaries" subtitle="Components whose rendered output passed the Figma parity gates.">
          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {catalog.verifiedCanaries.map((c) => (
              <div key={c.source} className="rounded-xl border border-utility-gray-200 bg-white p-4">
                <p className="font-mono text-xs text-utility-gray-900">{c.source}</p>
                <p className="mt-1 text-[11px] text-utility-gray-500">
                  {c.figma} · {c.specimens} verified specimen{c.specimens === 1 ? "" : "s"}
                </p>
              </div>
            ))}
          </div>
        </Section>
      </main>
    </div>
  );
}

createRoot(document.getElementById("catalog")!).render(<Catalog />);
