// GENERATED by compiler/figma/compile.mjs — the styling contract shared by button.tsx and button.theme.css.
// Figma axis values are on the left for traceability; the DOM only ever sees the public API values.

export type ButtonVariant = "link-color" | "link-gray" | "primary" | "secondary" | "tertiary";
export type ButtonSize = "lg" | "md" | "sm" | "xl" | "xs";
export type ButtonVisualState = "default" | "disabled" | "focused" | "hover" | "loading";

export const VARIANTS: ButtonVariant[] = ["link-color","link-gray","primary","secondary","tertiary"];
export const SIZES: ButtonSize[] = ["lg","md","sm","xl","xs"];

export const FIGMA_VARIANT: Record<ButtonVariant, string> = {
  "link-color": "Link color",
  "link-gray": "Link gray",
  "primary": "Primary",
  "secondary": "Secondary",
  "tertiary": "Tertiary",
};

/** Combinations the Figma component set does not define: rejected in dev, never styled. */
export const UNSUPPORTED: Array<{ variant: ButtonVariant; iconOnly: true }> = [{"variant":"link-color","iconOnly":true},{"variant":"link-gray","iconOnly":true}];

/** Variants that do define icon-only variants. */
export const SUPPORTS_ICON_ONLY: ButtonVariant[] = ["primary","secondary","tertiary"];
